BEGIN;
ALTER TABLE owners ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP(6);
ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP(6);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE IF NOT EXISTS platform_settings (
  key VARCHAR(50) PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT now()
);
COMMIT;
